### ISSUE TITLE
Dependency on .NET 3.5, gives false positive result of service install

### ISSUE THREAD

**Issue by dragsssss** [jon-hall/pm2-windows-service#24] opened 2017-01-18 04:20 UTC
Hi,

It appears as though there's a hard dependency on .net 3.5, which throws a windows error if .net 3.5 isn't installed.

When trying to install the windows service via command prompt (admin console) the console output says it has been successfully installed but windows throws an error because .NET 3.5 isn't installed. 
I would have thought there would be some sort of backwards compatibility with .NET 4.5.

I'm not sure if you'd want to do anything with this bug or update the documentation to state the dependencies. This may be a problem more so on corporate servers where dependencies need to be clearly defined and approved prior to installing software.

Anyway installed .NET 3.5 and the windows service has been working great so far. Thanks!

My setup:
Windows 2012 R2 64bit 
.NET 4.5 Installed 
Node.js v6.9.4

![image](https://cloud.githubusercontent.com/assets/520458/22050410/d2eced6c-dd8e-11e6-999e-a66ede0b0f41.png)

**Comment by jon-hall** [comment] 2017-01-22 15:49
Hi, thanks a lot for reporting this and my apologies for not getting back to you sooner.  Having checked over the small number of environments I currently have available to test this on, it looks like none of them have this specific set-up (.NET 4.5 but no .NET 3.5).  

I'll try to get a VM or something setup with this configuration as soon as I can so that I can reproduce the issue and try to figure out what can be done about it - my suspicion is that this is an upstream issue with the packages this library uses for installing/hosting the service, but I'll do some investigation to confirm.

I'll keep this issue updated with my findings, and will try to get the issue fixed if possible; failing that I'll make sure I add a note about the dependency to the README as you suggested.

**Comment by dragsssss** [comment] 2017-01-25 01:09
Cheers, thanks for that.

**Comment by ahctang** [comment] 2017-04-14 01:50
Hello!

Thanks for writing this program, it works great, except I've run into the same issue.

Do you have any idea what is causing the problem?

**Comment by adamsh25** [comment] 2017-11-21 09:25
Hi,

What actual feature in the PM2 service needs the dotnet 3.5?

Thank you,

**Comment by jon-hall** [comment] 2017-11-22 08:13
Hi, the dependency on .NET 3.5 is due to the upstream dependencies this package uses to create and install the service (node-windows, which itself uses winsw); here's one of the issues on node-windows which I believe is the same problem - https://github.com/coreybutler/node-windows/issues/47.

It seems that a PR was merged several months ago (https://github.com/coreybutler/node-windows/pull/153) which should have added support for .NET 4 without the requirement for .NET 2/.NET 3.5.  The way the dependencies are setup for this package, a fresh install should be pulling in the latest release of node-windows (`0.1.14`); so I'll need to try and recreate this issue and see if it has been solved by the upstream PR or if there's still an issue here to be fixed.

**Comment by tyamz** [comment] 2020-04-15 17:13
@jon-hall It has been over 2 years since your last reply. Has there been any updates on this issue?

**Comment by jon-hall** [comment] 2022-08-22 12:00
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).

**Closed as completed by jon-hall** 2022-08-22 12:00 UTC
Labels: bug
