### ISSUE TITLE
pm2 resurrect not being called on reboot

### ISSUE THREAD

**Issue by thebrianbug** [jon-hall/pm2-windows-service#27] opened 2017-05-26 15:14 UTC
The documentation says:

> If PM2_SERVICE_SCRIPTS is not set, then the default behavior is to call pm2 resurrect on service startup - when PM2 is running with the list of processes you want launched by the service, use pm2 save to dump the process list, ready for the service to restore it when it next starts.

I can't get this to work. When I run pm2-service-install, I've set all values except selecting no "n" for PM2_SERVICE_SCRIPTS. When I fill out PM2_SERVICE_SCRIPTS with index.js, my app is launched. However, I want to use non-default configuration including cluster mode.

I've gotten my configuration perfect with just pm2, then called `pm2 save`. When I restart, `pm2 list` shows no entries. When I manually call `pm2 resurrect` all my processes are successfully restored.

System info:
Windows Server 2012 R2 Standard
Latest pm2 and pm2-windows-service installed with npm -g.

How do I get this working? It's critical for our setup that we can restart an entire process list, not just a single service when we restart.

**Comment by thebrianbug** [comment] 2017-05-26 15:16
`node -v` v6.10.3
`pm2 -v` 2.4.6

**Comment by thebrianbug** [comment] 2017-05-26 15:21
Other related info: 

The service PM2 shows up as active in windows services on restart. When you first run `pm2 list` after a restart, pm2 is already started. It immediately shows the process grid, without the messages about starting up pm2. However, the process grid is empty.

And yes, all pm2 and pm2-windows-service commands were run from administrative power shell.

**Comment by jon-hall** [comment] 2017-05-27 10:47
Hi, thanks for providing so much info along with the issue and my apologies that this isn't working for you at the moment; as far as I can tell everything in your setup sounds fine.

Off the top of my head, the only thing you didn't mention which *may* be at fault is the value and visibility of the `PM2_HOME` environment variable.  If this is not visible, and set the same value, for the service user and your admin shell (and a path that's writable to all users) then I think the `pm2 save` from terminal won't be dumping to the same location the service loads from.  The way it's recommended to set this up is having it set at machine level and pointing to a directory which allows all users to read/write.

If that doesn't work, or you've already got `PM2_HOME` suitably setup, then let me know and I'll try my best at reproducing the issue and figuring out what's going wrong here.

**Comment by cognitivecarbon** [comment] 2017-08-20 17:09
I have the same issue; I noted the path where the windows service was pointing using the "services" control panel; and then from a command shell, tried to execute that same executable. e.g.

`c:\users\someUser\AppData\Roaming\npm\node_modules\pm2-windows-service\src\daemon\pm2.exe`

The error thrown in the the CMD shell is:
`system.IO.FileNotFoundException: Unable to locate pm2.xml file within executable directory or any parents`

Trying to find out what this xml file is, and why its missing.

**Comment by mitsukuri** [comment] 2017-09-08 17:17
Let me chime in too. While there's clearly a problem with `resurrect` not being called automatically, there is also a bug that prevents manual resurrection for processes in fork mode while they run under pm2-windows-service.

Consider these scenarios:

### Scenario 1: Fork mode
`pm2 start app.js`
`pm2 save`
`pm2 kill`
`pm2-service-install pm2`
`pm2 list` - empty process list!
`pm2 resurrect` - one process _errored_
`pm2-service-uninstall`
lets' see now...
`pm2 resurrect` - one process _online_!

### Scenario 2: Cluster mode
`pm2 start app.js -i 4`
`pm2 save`
`pm2 kill`
`pm2-service-install pm2`
`pm2 list` - empty process list as well
`pm2 resurrect` - all 4 processes _online_ now, even while running in pm2-windows-service!

Takeaway: something's preventing correct resurrection while the process is ran in pm2-windows-service.

`node -v` = `v6.11.2` | `npm -v` = `5.4.1` | `pm2 -v` = `2.6.1` | `pm2-windows-service@0.2.0`

Process error logs empty...

**Comment by frg** [comment] 2017-09-13 18:59
Same issue as @mitsukuri 

Node v6.10.3
PM2 v2.6.1

**Comment by jon-hall** [comment] 2017-09-16 14:45
@mitsukuri Thanks for the detailed reproductions steps, and my apologies it's taken me a while to get a chance to look into this.

Unfortunately, I've not been able to reproduce the first scenario you posted - after the `pm2 resurrect` with the service still installed and running, I get a running application in `pm2 list` (using the basic "Hello world" HTTP server from the node website as a test application).

There's a few more surrounding pieces of info I think I need to be able to understand why things aren't working for you:

- Do you have any of the environment variables related to this package or `pm2` setup (`PM2_SERVICE_SCRIPTS`, `PM2_HOME`, etc.), if so where are they set (user or machine) and what values to they have?
- What output do you see from `pm2` when you execute the scenario above (e.g. where does it say it dumped the process list to etc.)?
- Were you running the commands from `cmd`, `powershell`, or something else; and were they being run as Administrator, or under another user?
- What does `app.js` do? Does it perform file system access or anything else which might run into permissions issues? Also, is `app.js` located in a folder whose permissions will allow the service user to execute it?

I think that's all the info I'd need for a full reproduction, which will hopefully allow me to figure out how to get things working as expected from there.

**Comment by jon-hall** [comment] 2017-09-16 14:50
@cognitivecarbon Apologies in the delay on getting back to you, I believe the missing xml file is something generated by `node-windows` when it does the service creation/install for this package.  My best guess at fixing that would be:
- Run `pm2-service-uninstall` (if this fails, then manually uninstall any existing pm2 service with `sc delete <service name>`)
- Uninstall `pm2-windows-service`
- Reinstall `pm2-windows-service`
- Rerun `pm2-service-install` which should hopefully recreate the service and successfully output both the exe and xml files.

If it still isn't working for you please let me know and I can investigate further (any additional info you can provide on OS, node version, npm version, pm2 version etc. would all be helpful in this case).

**Comment by mitsukuri** [comment] 2017-09-16 17:18
@jon-hall No need to apologize and thank you for dedicating your time to this project!

- I've got only `PM2_HOME`=`C:\dev\web\pm2` set so far
- `$ pm2 start app.js`
`[PM2] Spawning PM2 daemon with pm2_home=C:\dev\web\pm2`
`[PM2] PM2 Successfully daemonized`
`[PM2] Starting C:\sites\test\app.js in fork_mode (1 instance)`
`[PM2] Done.`
 ` `
`$ pm2 save`
`[PM2] Saving current process list...`
`[PM2] Successfully saved in C:\dev\web\pm2\dump.pm2`
` `
`$ pm2 kill`
`[PM2] Stopping PM2...`
`[PM2] Applying action deleteProcessId on app [all](ids: 0)`
`[PM2] [app](0) ✓`
`[PM2] All processes have been stopped and deleted`
`[PM2] PM2 stopped`
` `
`$ pm2-service-install pm2`
`*** HINT: Run this as administrator to avoid the UAC spam ***`
`? Perform environment setup (recommended)? No`
`PM2 service installed and started.`
` `
`$ pm2 list`
`---empty table---`
` `
`$ pm2 resurrect`
`[PM2] Resurrecting`
`[PM2] Restoring processes located in C:\dev\web\pm2\dump.pm2`
`[PM2] Process C:\sites\test\app.js restored`
`│ app │ 0 │ fork │ N/A │ errored │ 0 │ 0 │ 0% │ 0 B │ user │ disabled │`
` `
`$ pm2-service-uninstall`
`PM2 service uninstalled.`
` `
`$ pm2 resurrect`
`[PM2] Spawning PM2 daemon with pm2_home=C:\dev\web\pm2`
`[PM2] PM2 Successfully daemonized`
`[PM2] Resurrecting`
`[PM2] Restoring processes located in C:\dev\web\pm2\dump.pm2`
`[PM2] Process C:\sites\test\app.js restored`
`│ app │ 0 │ fork │ 3856 │ online │ 0 │ 0s │ 0% │ 8.7 MB │ user │ disabled │`
- I'm running from conemu as admin, Windows 7, tried plain cmd to same effect
- My app.js is a primitive node/express 'hello world' at the moment :) The folder has full access, I even tried setting the permissions explicitly to Everyone - Full Access, didn't help.

**Comment by jon-hall** [comment] 2017-09-16 18:10
@mitsukuri Thanks for all the extra info, the only thing I can immediately think of which may be happening is that the service user doesn't have visibility of the `PM2_HOME` environment variable - which would mean it falls back to using the default of `C:\.pm2\`.

You can confirm this by checking to see if you have a `C:\.pm2\` folder; if you do, then try stopping the `pm2` service, deleting/renaming it, and then restarting the `pm2` service.  If the folder comes back then the service isn't seeing the `PM2_HOME` env var.  The fix for this this *should* be to make sure that it's set at the machine level rather than user level.

If this is not the case and the env var is set at machine level (meaning the service user should have visibility) then let me know and I'll continue to try and figure out what's going wrong.

**Comment by mitsukuri** [comment] 2017-09-16 19:32
There is no such directory on my disk, seems like it's respecting my PM2_HOME path!

**Comment by jon-hall** [comment] 2017-09-19 14:17
Thanks for checking into that for me @mitsukuri, unfortunately I'm a little out of ideas at this point on why your setup isn't working, since everything sounds fine with it.  The best thing I can think to do now is to try and gather some runtime info from the service to see if that reveals why it isn't able to work as expected.

I've got some work to do around a better logging setup for the service, but for now I've quickly thrown some crude logging into the service which should gather a lot of useful information for diagnosing your issue.

You can install this with:
```
npm i -g github:jon-hall/pm2-windows-service#feature/service_logging
```

It currently has no real configuration so you'll need to make sure there's a `C:\logs` folder for it to write its log file to.

After running `pm2-service-uninstall` (if you already have a service installed) and `pm2-service-install`, you should find the service is running and it has written some info to `C:\logs\pm2-windows-service.log`.

You'll want to check through and sanitise that information as required (it list all visible environment variables, current user info etc. - there might be nothing you need to scramble in there, but worth checking).  You can also probably trim out a lot from the environment variables if you want - provided you keep any that may be relevant (pm2 related, user related etc.).  Once you've done that, post the results here I can see if anything that it logs points to what's going wrong.

**Comment by mitsukuri** [comment] 2017-09-21 20:24
Here it is, stripped of all irrelevent entries:

`{
	"env":
	{
		"ALLUSERSPROFILE":"C:\\ProgramData",
		"APPDATA":"C:\\windows\\system32\\config\\systemprofile\\AppData\\Roaming",
		"BASE":"C:\\code\\web\\nodeJS\\node_modules\\pm2-windows-service\\src\\daemon\\pm2.exe",
		"CommonProgramFiles":"C:\\Program Files\\Common Files",
		"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
		"CommonProgramW6432":"C:\\Program Files\\Common Files",
		"HOME":"C:\\Users\\user",
		"LOCALAPPDATA":"C:\\windows\\system32\\config\\systemprofile\\AppData\\Local",
		"PM2_HOME":"C:\\code\\web\\pm2",
		"ProgramData":"C:\\ProgramData",
		"ProgramFiles":"C:\\Program Files",
		"ProgramFiles(x86)":"C:\\Program Files (x86)",
		"ProgramW6432":"C:\\Program Files",
		"SERVICE_ID":"pm2.exe",
		"SET_PM2_HOME":"true",
		"SET_PM2_SERVICE_PM2_DIR":"true",
		"SystemDrive":"C:",
		"SystemRoot":"C:\\windows",
		"TEMP":"C:\\windows\\TEMP",
		"TMP":"C:\\windows\\TEMP",
		"USERPROFILE":"C:\\windows\\system32\\config\\systemprofile",
		"windir":"C:\\windows",
		"WINSW_EXECUTABLE":"C:\\code\\web\\nodeJS\\node_modules\\pm2-windows-service\\src\\daemon\\pm2.exe",
	},
	"level":"info",
	"message":"ENV",
	"timestamp":"2017-09-21T19:57:26.221Z"
},
{
	"homedir":"C:\\windows\\system32\\config\\systemprofile",
	"level":"info",
	"message":"homedir",
	"timestamp":"2017-09-21T19:57:26.224Z"
},
{
	"userinfo":
	{
		"uid":-1,
		"gid":-1,
		"username":"SYSTEM",
		"homedir":"C:\\windows\\system32\\config\\systemprofile",
		"shell":null
	},
	"level":"info",
	"message":"userinfo",
	"timestamp":"2017-09-21T19:57:26.225Z"
}`

**Comment by jon-hall** [comment] 2017-09-22 11:06
Thanks a lot for running that and getting the log info back to me - the main thing I can see in there which may be the cause of this is:
```
"PM2_HOME":"C:\\code\\web\\pm2"
```

Whereas. when you were interacting with `pm2` over command line previously, it was writing using `"C:\dev\web\pm2"` as `PM2_HOME`, e.g.:
```
Restoring processes located in C:\dev\web\pm2\dump.pm2
```

Since the `PM2_HOME` being used by the service isn't just the default value, this is most likely caused by there being a `PM2_HOME` environment variable at machine-level which is pointing to `"C:\\code\\web\\pm2"`, and having one at user-level pointing to `"C:\dev\web\pm2"`.

#### Possible fixes

You should be able to forcibly update the machine-level value to match your user-level one by running
```
SETX PM2_HOME "C:\dev\web\pm2" /M
```
from an administrative powershell.

One other piece of info I spotted in the log, is that `pm2-windows-service` is installed in a non-standard directory - I'm guessing you have `npm.prefix` set to point to this directory, and so your global `pm2` is also installed there.  If that's the case, then you'll also need to manually point the service to where `pm2` is installed, since I don't think `npm.prefix` will be shared with the service user - you can do this with:
```
SETX PM2_SERVICE_PM2_DIR "C:\code\web\nodeJS\node_modules\pm2\" /M
```

If you can then restart the service and check the latest log entry to see if it's using the correct `PM2_HOME` afterwards.

If `PM2_HOME` for the service is now pointing to `"C:\dev\web\pm2"`, and the service is set to use the right copy of `pm2`, you should find that everything will start to work as expected, with the service and interactive `pm2` running the same `pm2` version, and sharing the same `PM2_HOME` directory.

Let me know how this goes, and if it still isn't working I'll see if there's anything else I can figure out that might be going on.

**Comment by jon-hall** [comment] 2017-10-21 13:49
Closing this, as there's been no activity in a while - feel free to reopen or open a new issue if any of the issues above are still unresolved.

**Closed as completed by jon-hall** 2017-10-21 13:49 UTC

**Comment by BinLiang1990** [comment] 2020-10-15 07:13
@jon-hall SETX PM2_HOME "C:\[xx]\.pm2" /M work form me. thanks
